- hosts: all
  tasks:
  - name: Install the latest version of Apache
    apt:
      name: apache2
      state: latest

  - name: Make sure a service is running
    service:
      name: apache2
      state: started
      enabled: yes

  - name: Install unzip
    package:
      name: unzip
      state: latest

  - name: Unarchive a file that needs to be downloaded 
    unarchive:
      src: https://www.free-css.com/assets/files/free-css-templates/download/page288/foste.zip
      dest: /var/www/
      remote_src: yes

  - name: Recursively change ownership of a directory
    file:
      path: /var/www/html
      state: directory
      recurse: yes
      owner: www-data
      group: www-data

      
